### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by TomTomGit86** [MrForExample/ComfyUI-AnimateAnyone-Evolved#14]
After installing animate anyone via comfyui, comfyui fails to stat giving this error message in the command window.

raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by NSFWAIgirl** [comment]
Had the same problem. Deleted the ComfyUI-AnimateAnyone-Evolved folder and ran update_comfyui_and_python_dependencies.bat made comfyui run again. Any solutions to this problem where I'll be able to use animateAnyone?

**Comment by TomTomGit86** [comment]
I managed to install Animate Anyone without that torch error now. Fresh Comfy install. Run update from update.bat (only Comfy), make sure the full path of `X:\....\python_embeded\Scripts`  is added in PATH in environment variables. Run Comfy once and fully close it. Git clone the manager in the custom_nodes. Run Comfy, let it install. When done, fully close it and run again. Install AnimateAnyone-Evolved via manager. Again, when installed, restart Comfy. If it works, now it shouldn't error out

**Comment by NSFWAIgirl** [comment]
> I managed to install Animate Anyone without that torch error now. Fresh Comfy install. Run update from update.bat (only Comfy), make sure the full path of `X:\....\python_embeded\Scripts` is added in PATH in environment variables. Run Comfy once and fully close it. Git clone the manager in the custom_nodes. Run Comfy, let it install. When done, fully close it and run again. Install AnimateAnyone-Evolved via manager. Again, when installed, restart Comfy. If it works, now it shouldn't error out

Yes this worked, didn't have to fully reinstall comfyui. Just added it to the PATH and then installed AnimateAnyone using the manager. Then restarted and getting no errors

**Comment by corvo4791** [comment]
> > I managed to install Animate Anyone without that torch error now. Fresh Comfy install. Run update from update.bat (only Comfy), make sure the full path of `X:\....\python_embeded\Scripts` is added in PATH in environment variables. Run Comfy once and fully close it. Git clone the manager in the custom_nodes. Run Comfy, let it install. When done, fully close it and run again. Install AnimateAnyone-Evolved via manager. Again, when installed, restart Comfy. If it works, now it shouldn't error out
> 
> Yes this worked, didn't have to fully reinstall comfyui. Just added it to the PATH and then installed AnimateAnyone using the manager. Then restarted and getting no errors

Would you be so kind to tell us what did you do, exactly? 
What did you add to PATH in environment variables?
Thanks.

**Comment by TomTomGit86** [comment]
If you search environment variables in Windows it should return the result for opening the windows settings to add environment variables in the top section (user) create/add a new PATH this cabe given a name that you choose but set the directory as above to you comfyui X:\....\python_embeded\Scripts
The x represent your drive letter and the dots represent the directory where you have it installed the last part is shown as it will be the same but the first part not as it will be different for each user. Once done this do as above on a fresh install of comfyui. Hope this helps. [
![Screenshot_20240130-124137](https://github.com/MrForExample/ComfyUI-AnimateAnyone-Evolved/assets/125327506/35d0315a-0af2-42a7-a53f-899e423cb3a3)
](url)

**Comment by corvo4791** [comment]
> If you search environment variables in Windows it should return the result for opening the windows settings to add environment variables in the top section (user) create/add a new PATH this can be given a name that you choose but set the directory as required X:....\python_embeded\Scripts The x represent your drive letter and the dots represent the directory where you have it installed. the last part is shown as it will be the same but the first part not as it will be different for each user. Once done this do as above on a fresh install of comfyui. Hope this helps. [ ![Screenshot_20240130-124137](https://private-user-images.githubusercontent.com/125327506/301146007-35d0315a-0af2-42a7-a53f-899e423cb3a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDc5NTgsIm5iZiI6MTcwNjcwNzY1OCwicGF0aCI6Ii8xMjUzMjc1MDYvMzAxMTQ2MDA3LTM1ZDAzMTVhLTBhZjItNDJhNy1hNTNmLTg5OWU0MjNjYjNhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxMzI3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjMzMmI5MTA0NGI1ZjZjM2UyMzJkZTNhMTYwNGI2YWYxMjIxOTFiMzIxYmY3YTBlYjJhN2U0OWVhNmVhYWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dx4n_b0CpfHZtuDwcCX_iDX2gsXyNb9zSkyL_UiGtj0) ](url)

Thanks, but, sadly, now I have a new error message:
Traceback (most recent call last):
  File "C:\code\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\code\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\__init__.py", line 8, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\code\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\nodes.py", line 22, in <module>
    from .src.models.unet_2d_condition import UNet2DConditionModel
  File "C:\code\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_condition.py", line 40, in <module>
    from .unet_2d_blocks import (
  File "C:\code\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\unet_2d_blocks.py", line 15, in <module>
    from .transformer_2d import Transformer2DModel
  File "C:\code\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved\src\models\transformer_2d.py", line 7, in <module>
    from diffusers.models.embeddings import PixArtAlphaTextProjection
ImportError: cannot import name 'PixArtAlphaTextProjection' from 'diffusers.models.embeddings' (C:\code\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)

Cannot import C:\code\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved module for custom nodes: cannot import name 'PixArtAlphaTextProjection' from 'diffusers.models.embeddings' (C:\code\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\embeddings.py)

**Comment by TomTomGit86** [comment]
I think you need to download the models required follow instructions in this video https://youtu.be/MGvx37ccCOM?si=rEvCba5wV57j8J9g

**Comment by corvo4791** [comment]
> I think you need to download the models required follow instructions in this video https://youtu.be/MGvx37ccCOM?si=rEvCba5wV57j8J9g

I already have downloaded all the models

**Comment by TomTomGit86** [comment]
> > I think you need to download the models required follow instructions in this video https://youtu.be/MGvx37ccCOM?si=rEvCba5wV57j8J9g
> 
> I already have downloaded all the models

Did you do all these new steps on a fresh comfyui install?

**Comment by corvo4791** [comment]
> > > I think you need to download the models required follow instructions in this video https://youtu.be/MGvx37ccCOM?si=rEvCba5wV57j8J9g
> > 
> > 
> > I already have downloaded all the models
> 
> Did you do all these new steps on a fresh comfyui install?

Yes, I did. Anyway, I solved here: https://github.com/MrForExample/ComfyUI-AnimateAnyone-Evolved/issues/15#issuecomment-1919179577

**Comment by TomTomGit86** [comment]
oh happy you got it solved, ohhhh this might solve my issue in nto beign able to pick a difrent sampler.

**Comment by badgids** [comment]
If anyone ever experiences the issue of Pytorch not being installed with Cuda (and you will :D it happens with many custom node installs), all you have to do is activate your ComfyUI virtual environment, then run the pip install command that's on the pytorch website for te correct version of pytorch with Cuda that you want.

https://pytorch.org/get-started/locally/

Cheers!

**Comment by alexanderdutton** [comment]
Doing the diffusers update alone (linked by corvo above) seemed to solve it for me -- thanks to everyone here for your efforts.

**Comment by nic0711** [comment]
Is there a solution for all the mac user? As M1-M3 have no CUDA device, torch is compiled without CUDA extension.
I get the error every time reaching the unet2d node.

**Comment by btech97** [comment]
> Is there a solution for all the mac user? As M1-M3 have no CUDA device, torch is compiled without CUDA extension. I get the error every time reaching the unet2d node.

Hey! Yes. I found this solution that did the trick: #27

**Comment by CrypteGuy** [comment]
I am having same problem but I am using StabilityMatrix I have a conda environment comfyenv. I can't use comfy portable solution. How do I fix my comfyUI and is this really a solution? If the custom node is going to do this every time when it is installed. Does anyone know why this is happening? pytorch is supposed to be uninstalled during the custom node installation process, so why is it not completing the installation to complete custom node installation process. Unless I am wrong, which does happen.
